version: "3"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "8006:80"
    environment:
      - PORT=80
      - HOST=0.0.0.0
      - NODE_ENV=production
